// Статические данные меню (используются как fallback если NocoDB недоступен)
// В продакшене данные загружаются из NocoDB

import type { Meal, ExtraItem, PortionSize } from "./types"

export const MEALS: Record<string, Meal[]> = {
  breakfast: [
    {
      id: 1,
      name: "Омлет с овощами",
      ingredients: "Яйца, помидоры, шпинат, сыр фета",
      description: "Воздушный омлет с сочными томатами, свежим шпинатом и нежным сыром фета",
      prices: { single: 280, medium: 350, large: 420 },
      weights: { single: 250, medium: 350, large: 450 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/omelet-with-vegetables-tomatoes-spinach-feta-chees.jpg",
      available: true,
      nutrition: { calories: 245, protein: 18, fats: 16, carbs: 8, weight: 250 },
      category: "breakfast",
      weekType: "both",
    },
    {
      id: 2,
      name: "Овсяная каша",
      ingredients: "Овсянка, банан, ягоды, мед, орехи",
      description: "Полезная овсянка с натуральным медом, свежими ягодами и хрустящими орехами",
      prices: { single: 250, medium: 320, large: 390 },
      weights: { single: 300, medium: 400, large: 500 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/oatmeal-with-banana-berries-honey-nuts.jpg",
      available: true,
      nutrition: { calories: 320, protein: 12, fats: 8, carbs: 52, weight: 300 },
      category: "breakfast",
      weekType: "both",
    },
    {
      id: 3,
      name: "Сырники",
      ingredients: "Творог, мука, яйца, сметана, ягодный соус",
      description: "Классические сырники из домашнего творога со сметаной и ягодным соусом",
      prices: { single: 320, medium: 400, large: 480 },
      weights: { single: 280, medium: 380, large: 480 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/russian-syrniki-pancakes-with-sour-cream-berry-sau.jpg",
      available: true,
      nutrition: { calories: 380, protein: 16, fats: 14, carbs: 46, weight: 280 },
      category: "breakfast",
      weekType: "current",
    },
    {
      id: 4,
      name: "Панкейки",
      ingredients: "Мука, молоко, яйца, кленовый сироп",
      description: "Пышные американские панкейки с натуральным кленовым сиропом",
      prices: { single: 290, medium: 360, large: 430 },
      weights: { single: 250, medium: 350, large: 450 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/pancakes-maple-syrup.png",
      available: true,
      nutrition: { calories: 340, protein: 10, fats: 8, carbs: 58, weight: 250 },
      category: "breakfast",
      weekType: "next",
    },
  ],
  lunch_salad: [
    {
      id: 10,
      name: "Салат Греческий",
      ingredients: "Огурцы, помидоры, перец, маслины, фета, оливковое масло",
      description: "Свежий средиземноморский салат с сыром фета и оливковым маслом",
      prices: { single: 340, medium: 420, large: 500 },
      weights: { single: 220, medium: 320, large: 420 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/greek-salad.jpg",
      available: true,
      nutrition: { calories: 280, protein: 8, fats: 22, carbs: 12, weight: 220 },
      category: "lunch_salad",
      weekType: "both",
    },
    {
      id: 11,
      name: "Салат с тунцом",
      ingredients: "Тунец, яйцо, фасоль, помидоры, салат, оливки",
      description: "Сытный салат Нисуаз с консервированным тунцом и фасолью",
      prices: { single: 420, medium: 520, large: 620 },
      weights: { single: 280, medium: 380, large: 480 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/tuna-salad-nicoise.jpg",
      available: true,
      nutrition: { calories: 320, protein: 26, fats: 18, carbs: 14, weight: 280 },
      category: "lunch_salad",
      weekType: "current",
    },
    {
      id: 12,
      name: "Салат Цезарь",
      ingredients: "Курица, салат ромэн, пармезан, гренки, соус",
      description: "Классический Цезарь с нежной курицей и хрустящими гренками",
      prices: { single: 380, medium: 470, large: 560 },
      weights: { single: 260, medium: 360, large: 460 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/caesar-salad-with-chicken-parmesan-croutons.jpg",
      available: true,
      nutrition: { calories: 350, protein: 28, fats: 20, carbs: 16, weight: 260 },
      category: "lunch_salad",
      weekType: "next",
    },
  ],
  lunch_soup: [
    {
      id: 20,
      name: "Борщ",
      ingredients: "Свекла, капуста, говядина, картофель, сметана",
      description: "Традиционный украинский борщ на говяжьем бульоне со сметаной",
      prices: { single: 320, medium: 400, large: 480 },
      weights: { single: 350, medium: 450, large: 550 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/borscht-soup-with-sour-cream.jpg",
      available: true,
      nutrition: { calories: 240, protein: 14, fats: 10, carbs: 24, weight: 350 },
      category: "lunch_soup",
      weekType: "both",
    },
    {
      id: 21,
      name: "Куриный суп",
      ingredients: "Курица, лапша, морковь, лук, зелень",
      description: "Домашний куриный суп с лапшой и свежей зеленью",
      prices: { single: 280, medium: 350, large: 420 },
      weights: { single: 350, medium: 450, large: 550 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/chicken-noodle-soup.jpg",
      available: true,
      nutrition: { calories: 180, protein: 16, fats: 6, carbs: 18, weight: 350 },
      category: "lunch_soup",
      weekType: "current",
    },
    {
      id: 22,
      name: "Крем-суп из тыквы",
      ingredients: "Тыква, сливки, имбирь, семечки",
      description: "Нежный крем-суп из печеной тыквы с имбирем и тыквенными семечками",
      prices: { single: 300, medium: 380, large: 460 },
      weights: { single: 300, medium: 400, large: 500 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/pumpkin-cream-soup.jpg",
      available: true,
      nutrition: { calories: 220, protein: 6, fats: 14, carbs: 20, weight: 300 },
      category: "lunch_soup",
      weekType: "next",
    },
  ],
  lunch_main: [
    {
      id: 30,
      name: "Куриная грудка",
      ingredients: "Филе курицы, специи, оливковое масло",
      description: "Сочная куриная грудка на гриле с ароматными травами",
      prices: { single: 380, medium: 470, large: 560 },
      weights: { single: 180, medium: 260, large: 340 },
      portion: "single" as PortionSize,
      needsGarnish: true,
      image: "/grilled-chicken-breast-with-herbs.jpg",
      available: true,
      nutrition: { calories: 210, protein: 38, fats: 6, carbs: 2, weight: 180 },
      category: "lunch_main",
      weekType: "both",
    },
    {
      id: 31,
      name: "Лосось на гриле",
      ingredients: "Стейк лосося, лимон, укроп",
      description: "Стейк норвежского лосося на гриле с лимоном и укропом",
      prices: { single: 580, medium: 720, large: 860 },
      weights: { single: 200, medium: 280, large: 360 },
      portion: "single" as PortionSize,
      needsGarnish: true,
      image: "/grilled-salmon-steak-with-lemon-dill.jpg",
      available: true,
      nutrition: { calories: 320, protein: 34, fats: 20, carbs: 0, weight: 200 },
      category: "lunch_main",
      weekType: "current",
    },
    {
      id: 32,
      name: "Паста Карбонара",
      ingredients: "Спагетти, бекон, сливки, пармезан, яйцо",
      description: "Классическая итальянская паста с беконом и сливочным соусом",
      prices: { single: 420, medium: 520, large: 620 },
      weights: { single: 320, medium: 420, large: 520 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/pasta-carbonara-with-bacon-parmesan.jpg",
      available: true,
      nutrition: { calories: 520, protein: 22, fats: 26, carbs: 48, weight: 320 },
      category: "lunch_main",
      weekType: "next",
    },
  ],
  dinner_salad: [
    {
      id: 40,
      name: "Салат Оливье",
      ingredients: "Картофель, морковь, горошек, яйца, колбаса, майонез",
      description: "Классический русский салат с домашним майонезом",
      prices: { single: 280, medium: 360, large: 440 },
      weights: { single: 250, medium: 350, large: 450 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/olivier-salad-russian.jpg",
      available: true,
      nutrition: { calories: 340, protein: 12, fats: 22, carbs: 24, weight: 250 },
      category: "dinner_salad",
      weekType: "both",
    },
    {
      id: 41,
      name: "Салат Витаминный",
      ingredients: "Капуста, морковь, болгарский перец, яблоко, лимонный сок",
      description: "Легкий витаминный салат из свежих овощей с яблоком",
      prices: { single: 220, medium: 280, large: 340 },
      weights: { single: 200, medium: 300, large: 400 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/vitamin-salad-cabbage.jpg",
      available: true,
      nutrition: { calories: 120, protein: 3, fats: 2, carbs: 22, weight: 200 },
      category: "dinner_salad",
      weekType: "current",
    },
    {
      id: 42,
      name: "Салат с авокадо",
      ingredients: "Авокадо, руккола, черри, кедровые орехи, пармезан",
      description: "Изысканный салат с авокадо, рукколой и кедровыми орешками",
      prices: { single: 390, medium: 480, large: 570 },
      weights: { single: 200, medium: 300, large: 400 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/avocado-salad-arugula.jpg",
      available: true,
      nutrition: { calories: 320, protein: 8, fats: 28, carbs: 12, weight: 200 },
      category: "dinner_salad",
      weekType: "next",
    },
  ],
  dinner_soup: [
    {
      id: 50,
      name: "Окрошка",
      ingredients: "Квас, огурцы, редис, яйца, колбаса, зелень, сметана",
      description: "Освежающий холодный суп на квасе с овощами",
      prices: { single: 290, medium: 370, large: 450 },
      weights: { single: 350, medium: 450, large: 550 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/okroshka-cold-soup.jpg",
      available: true,
      nutrition: { calories: 180, protein: 10, fats: 8, carbs: 18, weight: 350 },
      category: "dinner_soup",
      weekType: "both",
    },
    {
      id: 51,
      name: "Грибной крем-суп",
      ingredients: "Шампиньоны, сливки, лук, чеснок, зелень",
      description: "Ароматный крем-суп из шампиньонов со сливками",
      prices: { single: 310, medium: 390, large: 470 },
      weights: { single: 300, medium: 400, large: 500 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/mushroom-cream-soup.jpg",
      available: true,
      nutrition: { calories: 200, protein: 6, fats: 16, carbs: 10, weight: 300 },
      category: "dinner_soup",
      weekType: "current",
    },
    {
      id: 52,
      name: "Уха",
      ingredients: "Рыба, картофель, морковь, лук, зелень",
      description: "Наваристая уха из свежей рыбы с овощами",
      prices: { single: 350, medium: 440, large: 530 },
      weights: { single: 350, medium: 450, large: 550 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/fish-soup-ukha.jpg",
      available: true,
      nutrition: { calories: 160, protein: 18, fats: 4, carbs: 14, weight: 350 },
      category: "dinner_soup",
      weekType: "next",
    },
  ],
  dinner_main: [
    {
      id: 60,
      name: "Стейк из индейки",
      ingredients: "Филе индейки, травы, чеснок",
      description: "Сочный стейк из индейки с ароматными травами",
      prices: { single: 420, medium: 520, large: 620 },
      weights: { single: 180, medium: 260, large: 340 },
      portion: "single" as PortionSize,
      needsGarnish: true,
      image: "/turkey-steak-with-herbs-garlic.jpg",
      available: true,
      nutrition: { calories: 190, protein: 36, fats: 4, carbs: 2, weight: 180 },
      category: "dinner_main",
      weekType: "both",
    },
    {
      id: 61,
      name: "Треска запеченная",
      ingredients: "Филе трески, овощи, лимон",
      description: "Запеченное филе трески с овощами и лимоном",
      prices: { single: 480, medium: 600, large: 720 },
      weights: { single: 220, medium: 300, large: 380 },
      portion: "single" as PortionSize,
      needsGarnish: true,
      image: "/baked-cod-fish-with-vegetables-lemon.jpg",
      available: true,
      nutrition: { calories: 180, protein: 32, fats: 4, carbs: 6, weight: 220 },
      category: "dinner_main",
      weekType: "current",
    },
    {
      id: 62,
      name: "Котлеты домашние",
      ingredients: "Говядина, свинина, лук, яйцо, специи",
      description: "Сочные домашние котлеты из мясного фарша",
      prices: { single: 360, medium: 450, large: 540 },
      weights: { single: 200, medium: 280, large: 360 },
      portion: "single" as PortionSize,
      needsGarnish: true,
      image: "/homemade-cutlets.jpg",
      available: true,
      nutrition: { calories: 320, protein: 28, fats: 22, carbs: 4, weight: 200 },
      category: "dinner_main",
      weekType: "next",
    },
  ],
  garnish: [
    {
      id: 70,
      name: "Гречка",
      ingredients: "Гречневая крупа, соль",
      description: "Рассыпчатая гречневая каша",
      prices: { single: 80, medium: 110, large: 140 },
      weights: { single: 150, medium: 220, large: 290 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/buckwheat-garnish.jpg",
      available: true,
      nutrition: { calories: 110, protein: 4, fats: 1, carbs: 22, weight: 150 },
      category: "garnish",
      weekType: "both",
    },
    {
      id: 71,
      name: "Рис",
      ingredients: "Белый рис басмати, соль",
      description: "Ароматный рис басмати",
      prices: { single: 70, medium: 100, large: 130 },
      weights: { single: 150, medium: 220, large: 290 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/white-rice-garnish.jpg",
      available: true,
      nutrition: { calories: 130, protein: 3, fats: 0, carbs: 28, weight: 150 },
      category: "garnish",
      weekType: "both",
    },
    {
      id: 72,
      name: "Овощи на пару",
      ingredients: "Брокколи, морковь, цветная капуста",
      description: "Овощной микс на пару",
      prices: { single: 100, medium: 140, large: 180 },
      weights: { single: 150, medium: 220, large: 290 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/steamed-vegetables-garnish.jpg",
      available: true,
      nutrition: { calories: 60, protein: 3, fats: 0, carbs: 12, weight: 150 },
      category: "garnish",
      weekType: "both",
    },
    {
      id: 73,
      name: "Картофельное пюре",
      ingredients: "Картофель, молоко, сливочное масло, соль",
      description: "Нежное картофельное пюре",
      prices: { single: 90, medium: 130, large: 170 },
      weights: { single: 150, medium: 220, large: 290 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/mashed-potatoes-garnish.jpg",
      available: true,
      nutrition: { calories: 140, protein: 3, fats: 4, carbs: 24, weight: 150 },
      category: "garnish",
      weekType: "both",
    },
    {
      id: 74,
      name: "Киноа",
      ingredients: "Белая киноа, соль, специи",
      description: "Полезная киноа со специями",
      prices: { single: 110, medium: 150, large: 190 },
      weights: { single: 150, medium: 220, large: 290 },
      portion: "single" as PortionSize,
      needsGarnish: false,
      image: "/quinoa-garnish.jpg",
      available: true,
      nutrition: { calories: 120, protein: 5, fats: 2, carbs: 21, weight: 150 },
      category: "garnish",
      weekType: "both",
    },
  ],
}

export const EXTRAS: Record<string, ExtraItem[]> = {
  drink: [
    {
      id: 100,
      name: "Морс клюквенный",
      price: 120,
      image: "/cranberry-mors-drink.jpg",
      available: true,
      ingredients: "Клюква, вода, сахар",
      description: "Освежающий морс из свежей клюквы",
      nutrition: { calories: 80, protein: 0, fats: 0, carbs: 20, weight: 250 },
      category: "drink",
    },
    {
      id: 101,
      name: "Компот из сухофруктов",
      price: 100,
      image: "/dried-fruit-compote.jpg",
      available: true,
      ingredients: "Курага, чернослив, изюм, вода, сахар",
      description: "Традиционный компот из сухофруктов",
      nutrition: { calories: 90, protein: 1, fats: 0, carbs: 22, weight: 250 },
      category: "drink",
    },
    {
      id: 102,
      name: "Лимонад домашний",
      price: 150,
      image: "/homemade-lemonade.jpg",
      available: true,
      ingredients: "Лимон, вода, сахар, мята",
      description: "Домашний лимонад с мятой",
      nutrition: { calories: 70, protein: 0, fats: 0, carbs: 18, weight: 250 },
      category: "drink",
    },
    {
      id: 103,
      name: "Смузи ягодный",
      price: 180,
      image: "/berry-smoothie.jpg",
      available: true,
      ingredients: "Клубника, черника, банан, йогурт",
      description: "Густой ягодный смузи с йогуртом",
      nutrition: { calories: 140, protein: 4, fats: 2, carbs: 28, weight: 250 },
      category: "drink",
    },
  ],
  sauce: [
    {
      id: 110,
      name: "Соус сырный",
      price: 60,
      image: "/cheese-sauce.jpg",
      available: true,
      ingredients: "Сыр, сливки, чеснок, специи",
      description: "Нежный сливочно-сырный соус",
      nutrition: { calories: 180, protein: 6, fats: 16, carbs: 4, weight: 50 },
      category: "sauce",
    },
    {
      id: 111,
      name: "Соус томатный",
      price: 50,
      image: "/tomato-sauce.jpg",
      available: true,
      ingredients: "Томаты, лук, чеснок, базилик",
      description: "Классический томатный соус",
      nutrition: { calories: 60, protein: 2, fats: 2, carbs: 10, weight: 50 },
      category: "sauce",
    },
    {
      id: 112,
      name: "Соус чесночный",
      price: 55,
      image: "/garlic-sauce.jpg",
      available: true,
      ingredients: "Чеснок, майонез, укроп",
      description: "Пикантный чесночный соус",
      nutrition: { calories: 220, protein: 1, fats: 24, carbs: 2, weight: 50 },
      category: "sauce",
    },
    {
      id: 113,
      name: "Песто",
      price: 80,
      image: "/pesto-sauce.jpg",
      available: true,
      ingredients: "Базилик, кедровые орехи, пармезан, масло",
      description: "Итальянский соус песто",
      nutrition: { calories: 240, protein: 4, fats: 24, carbs: 4, weight: 50 },
      category: "sauce",
    },
  ],
  dessert: [
    {
      id: 120,
      name: "Тирамису",
      price: 280,
      image: "/tiramisu-dessert.jpg",
      available: true,
      ingredients: "Маскарпоне, савоярди, кофе, какао",
      description: "Классический итальянский десерт",
      nutrition: { calories: 320, protein: 6, fats: 18, carbs: 34, weight: 120 },
      category: "dessert",
    },
    {
      id: 121,
      name: "Чизкейк",
      price: 260,
      image: "/cheesecake-dessert.jpg",
      available: true,
      ingredients: "Сливочный сыр, печенье, сахар, сливки",
      description: "Нежный чизкейк Нью-Йорк",
      nutrition: { calories: 380, protein: 8, fats: 24, carbs: 32, weight: 130 },
      category: "dessert",
    },
    {
      id: 122,
      name: "Панна котта",
      price: 220,
      image: "/panna-cotta-dessert.jpg",
      available: true,
      ingredients: "Сливки, сахар, ваниль, желатин, ягоды",
      description: "Итальянский десерт с ягодами",
      nutrition: { calories: 280, protein: 4, fats: 18, carbs: 26, weight: 110 },
      category: "dessert",
    },
    {
      id: 123,
      name: "Брауни",
      price: 180,
      image: "/brownie-dessert.jpg",
      available: true,
      ingredients: "Шоколад, масло, яйца, мука, орехи",
      description: "Шоколадный брауни с орехами",
      nutrition: { calories: 340, protein: 6, fats: 20, carbs: 36, weight: 100 },
      category: "dessert",
    },
  ],
}

export const DELIVERY_TIMES = ["18:00 - 19:00", "19:00 - 20:00", "20:00 - 21:00", "21:00 - 22:00"]

export function getMealsForWeek(weekType: "current" | "next"): Record<string, Meal[]> {
  const filtered: Record<string, Meal[]> = {}

  for (const [category, meals] of Object.entries(MEALS)) {
    filtered[category] = meals.filter((meal) => meal.weekType === "both" || meal.weekType === weekType)
  }

  return filtered
}

export function isMealAvailable(mealName: string, weekType?: "current" | "next"): boolean {
  const allMeals = Object.values(MEALS).flat()
  const meal = allMeals.find((m) => m.name === mealName)

  if (!meal) return false

  // Доступность определяется только через weekType
  if (weekType) {
    return meal.weekType === "both" || meal.weekType === weekType
  }

  // Если weekType не указан, блюдо доступно если есть weekType
  return !!meal.weekType
}

export function isExtraAvailable(extraName: string, weekType?: "current" | "next"): boolean {
  const allExtras = Object.values(EXTRAS).flat()
  const extra = allExtras.find((e) => e.name === extraName)
  if (!extra) return false
  
  // Для статических данных (fallback) считаем доступными, если есть
  // В реальности доступность определяется через isCurrentWeek/isNextWeek из NocoDB
  // Но для статических данных просто проверяем наличие
  return true
}

export function getGarnishes(): Meal[] {
  return MEALS.garnish || []
}

export function getMealById(id: number): Meal | undefined {
  return Object.values(MEALS)
    .flat()
    .find((m) => m.id === id)
}

export function getExtraById(id: number): ExtraItem | undefined {
  return Object.values(EXTRAS)
    .flat()
    .find((e) => e.id === id)
}
